### ISSUE TITLE
Unknown DOM property: enable-background

### ISSUE THREAD

**Issue by johntran** [codefoundries/material-ui-credit-card-icons#2]
![screen shot 2016-08-15 at 11 54 47 am](https://cloud.githubusercontent.com/assets/3813391/17675566/1ed4ed22-62df-11e6-812c-d8bda9014fb9.png)

React error when using icons

**Comment by thelordoftheboards** [comment]
What version of react and react-dom are you using?

**Comment by johntran** [comment]
React: 15.3.0
React-DOM: 15.3.0

**Comment by thelordoftheboards** [comment]
Thank you. It does not seem to happen for me with 15.2.1 I will look to upgrade to 15.3 to verify.
